name: Python application Setup - Chat GPT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install setuptools --upgrade
        python -m pip install pydantic[email]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      #run: |
        #python -m pytest
    - name : Test with pytest Code Coverage
      #run: |
        #python -m pytest --cov=OpenAI
    ##- name : Pip audit check
      ##run: |
        ##pip-audit

